// This file is auto generated by /tools/AstGenerator.go

package ast

import . "gka.com/front-end"

type Expr interface {
	Print() string
	exprNode()
}

type (
	AssignExpr struct {
		Name  Token
		Value Expr
	}
	BinaryExpr struct {
		Left     Expr
		Operator Token
		Right    Expr
	}
	CallExpr struct {
		Callee    Expr
		Paren     Token
		Arguments []Expr
	}
	GetExpr struct {
		Object Expr
		Name   Token
	}
	GroupingExpr struct {
		Expression Expr
	}
	LiteralExpr struct {
		Value string
	}
	LogicalExpr struct {
		Left     Expr
		Operator Token
		Right    Expr
	}
	SetExpr struct {
		Object Expr
		Name   Token
		Value  Expr
	}
	SuperExpr struct {
		Keyword Token
		Method  Token
	}
	ThisExpr struct {
		Keyword Token
	}
	UnaryExpr struct {
		Operator Token
		Right    Expr
	}
	VariableExpr struct {
		Name Token
	}
)

// Ensure that only Expr nodes can be assigned to Expr fields
func (*AssignExpr) exprNode()   {}
func (*BinaryExpr) exprNode()   {}
func (*CallExpr) exprNode()     {}
func (*GetExpr) exprNode()      {}
func (*GroupingExpr) exprNode() {}
func (*LiteralExpr) exprNode()  {}
func (*LogicalExpr) exprNode()  {}
func (*SetExpr) exprNode()      {}
func (*SuperExpr) exprNode()    {}
func (*ThisExpr) exprNode()     {}
func (*UnaryExpr) exprNode()    {}
func (*VariableExpr) exprNode() {}
